// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function AddPhrase(arg1:number,arg2:string,arg3:string):Promise<boolean>;

export function DeletePhrase(arg1:number):Promise<boolean>;

export function GetCategories():Promise<Array<db.Category>>;

export function GetHistory(arg1:number):Promise<Array<string>>;

export function GetPhrases(arg1:number):Promise<Array<db.Phrase>>;

export function HideWindow():Promise<void>;

export function IsAutoStartEnabled():Promise<boolean>;

export function PasteText(arg1:string):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<boolean>;

export function ToggleWindow():Promise<void>;
