// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPhrase(arg1, arg2, arg3) {
  return window['go']['backend']['App']['AddPhrase'](arg1, arg2, arg3);
}

export function ClearFifoQueue() {
  return window['go']['backend']['App']['ClearFifoQueue']();
}

export function DeletePhrase(arg1) {
  return window['go']['backend']['App']['DeletePhrase'](arg1);
}

export function GetCategories() {
  return window['go']['backend']['App']['GetCategories']();
}

export function GetFifoQueue() {
  return window['go']['backend']['App']['GetFifoQueue']();
}

export function GetHistory(arg1) {
  return window['go']['backend']['App']['GetHistory'](arg1);
}

export function GetPhrases(arg1) {
  return window['go']['backend']['App']['GetPhrases'](arg1);
}

export function HideWindow() {
  return window['go']['backend']['App']['HideWindow']();
}

export function IsAutoStartEnabled() {
  return window['go']['backend']['App']['IsAutoStartEnabled']();
}

export function IsFifoMode() {
  return window['go']['backend']['App']['IsFifoMode']();
}

export function PasteText(arg1) {
  return window['go']['backend']['App']['PasteText'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['backend']['App']['SetAutoStart'](arg1);
}

export function ToggleFifoMode() {
  return window['go']['backend']['App']['ToggleFifoMode']();
}

export function ToggleWindow() {
  return window['go']['backend']['App']['ToggleWindow']();
}
